spring:
  datasource:
    url: jdbc:mysql://39.108.230.146:3306/hwjl?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Forever522.
    druid:
      initial-size: 1  # 连接池初始化大小
      min-idle: 5     # 最小空闲连接数
      max-active:  10
      web-stat-filter:
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  #不统计这些请求数据

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug
  file:
    name: weblog
    path: ./

mybatis:
  mapper-locations: classpath:mapper/*.xml
