
spring:
  datasource:
    url: jdbc:mysql://39.108.230.146:3306/wifi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    druid:
      initial-size: 1  # 连接池初始化大小
      min-idle: 5     # 最小空闲连接数
      max-active:  10
      web-stat-filter:
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"  #不统计这些请求数据
  jackson:  # 解决接口出现实体类字段为null
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /static/**

logging:
  config: classpath:logback-spring.xml
  level:
    com:
      wifi:
        server:
          module:
            dao: debug
    org:
      mybatis: debug
  file:
    name: wifi_data_log
    path: /usr/local/tomcat8/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wifi.server.module.entity
server:
  servlet:
    context-path: /wifi-server
  port: 80